### ISSUE TITLE
[Bug report]  The grow_to_target function used by AstrocyteGrower class has a an infinite loop

### ISSUE THREAD

**Issue by jacquemi-bbp** [BlueBrain/NeuroTS#103]
### Describe the bug

The grow_to_target function astrocyte/section.py#L35  function used by AstrocyteGrower class has a an infinite loop https://github.com/BlueBrain/NeuroTS/blob/d47bf8d6448ad8290021ae8a24e69eaae6dbb203/neurots/

It is because one always adds the same reference to the point  object in a list instead of a new point object.
https://github.com/BlueBrain/NeuroTS/blob/d47bf8d6448ad8290021ae8a24e69eaae6dbb203/neurots/astrocyte/section.py#L68C8-L68C29

### To Reproduce

```Python
I can provide a script and the needed inputs to reproduce the bug,
```

### Error

```Python traceback
infinite loop
```

### neurots Version in Use

NeuroTS==3.5.0

### Python Version

3.10

### Operating system

Linux

**Comment by jacquemi-bbp** [comment]
I will propose a PR to correct this BUG.

**Comment by eleftherioszisis** [comment]
Please provide a script to reproduce the bug. :)
